version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/data/db
      - NODE_ENV=production
    volumes:
      - ./data:/data
    networks:
      - baby-tracker-network

networks:
  baby-tracker-network:
    driver: bridge
