# fly.toml app configuration file generated for baby-tracker-still-sound-6194 on 2025-09-19T18:08:46+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'baby-tracker-still-sound-6194'
primary_region = 'fra'

[build]

[env]
DATABASE_URL = "file:/data/db"

[processes]
app = "node dbsetup.js npm run start -- --host 0.0.0.0 --port 3000"

[mounts]
source = "data"
destination = "/data"
auto_extend_size_threshold = 50
auto_extend_size_increment = "1GB"
auto_extend_size_limit = "10GB"


[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'off'
auto_start_machines = false
min_machines_running = 0
processes = ['app']


[[vm]]
memory = '256m'
cpu_kind = 'shared'
cpus = 1
